# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  - job_name: 'gist-grapper'
    static_configs:
    - targets: ['localhost:3000']

remote_write:
- url: https://prometheus-prod-10-prod-us-central-0.grafana.net/api/prom/push
  basic_auth:
    username: 269734
    password: eyJrIjoiY2MxMzc4MzFlZDQ2MzA0YTAyYmU0ZDc2MWRhMTgwNDMwMTY1NGQ3NiIsIm4iOiJsb2NhbCIsImlkIjo1NzI5Mjd9
