version: "3.4"
services:
  mongo:
    image: mongo:3.6.6-jessie
    container_name: 'pd-mongo'
    ports:
      - '27017:27017'
    volumes:
      - './.docker/compose/mongo/db:/data/db'
      - './.docker/compose/mongo/restore:/data/restore:ro'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=dev-pipedrive

  mongo-express:
    image: mongo-express
    container_name: 'pd-mongo-express'
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=dev-pipedrive
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'pd-rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - './.docker/compose/data/rabbitmq/data/:/var/lib/rabbitmq/'
      - './.docker/compose/data/rabbitmq/log/:/var/log/rabbitmq'
